### ISSUE TITLE
Need help with Linear Blend Skinning 

### ISSUE THREAD

**Issue by resindraburiza** [marcbadger/avian-mesh#6]
Hello Marc Badger,

Once again, thank you very much for sharing the code. I have been studying the code for a while using the suggestion you gave in my previous issue, but I found LBS (https://github.com/marcbadger/avian-mesh/blob/master/models/LBS.py#L25) a little bit hard to understand. I would like to ask some things and I hope that you can help explain about it.

First, about line 36:
```
T[:, :, :3, :] = torch.cat([pose, kin_tree], dim=-1)
```
It seems that T is a collection of forward kinematics describing the rotation and translation of a joint and link. Is my understanding correct?

Second, about line 37-40:
```
T_rel = [T[:, 0]]
for i in range(1, self.n_joints):
      T_rel.append(T_rel[self.parents[i]] @ T[:, i])
T_rel = torch.stack(T_rel, dim=1)
```
This one is just chaining the joint kinematics from the root (0,0,0) to terminal node, right?

Third, about line 41:
```
T_rel[:,:,:,[-1]] -= T_rel.clone() @ (self.h_joints*scale)
```
This one I cannot understand. I think that `T_rel` it self is a chained [R|t] of any branch in the kinematic tree. Then by calculating it, we can get the end effector/terminal node. But, why you have to calculate `T_rel.clone() @ (self.h_joints*scale)`? WIll this gets you a new effector/terminal node positions? Then, why you have to subtract it from the chained T_rel `T_rel[:,:,:,[-1]]`?

Lastly, about line 44:
```
V = T_ @ V
```
This one just transform the vertices based on the wighted `T_`. Everything in LBS process are done in bird model coordinate. Is it correct?

I am sorry if those are rookie questions. Thank you very much.

Best regards,
Resindra

**Comment by yufu-wang** [comment]
Resindra, we are sorry for this very late reply. If it is still useful for you:
1. at line 36, T is the set of configuration for each joint w.r.t **its parent**. Your understanding is correct.
2. at line 37-40,  T_rel is the joints' configurations w.r.t the **root joint**. We obtain them by forward kinematics. 
3. at line 41, T_rel is adjusted, w.r.t the **default configuration**. We could have given this variable another name. Before this line, T_rel describes each joint's conf wrt root. But what we want to know is how they have moved wrt the rest position. For example, if the model did not articulate, before line 41, T_rel describes the joints in this default/resting configuration; after line 41, T_rel will have all its R to be identity matrix and t to be zero translation. T_rel is the transformation that we actually need to apply.
4. at line 42-44, we obtain the weighted transformations for each vertex and apply them. The LBS procedure should probably be considered to be in global coordinate, because we do allow the root joint to rotate. However, we apply global translation outside of LBS.

Best regard.

**Comment by resindraburiza** [comment]
Hi Yufu-Wang,

thank you so much for getting back for my question. Now I can understand your LBS implementation quite well. Thank you.

Best regards,
resindra
